"""
CEO Briefing Generator - Weekly/Monthly Business Reports

Generates comprehensive business briefings by analyzing:
- Completed tasks
- Revenue/accounting data
- Email communications
- Social media activity
- Business goals progress

Usage:
    python ceo_briefing.py --vault "C:/Vault" --period "last_week"
"""

import sys
import io
import json
import argparse
from pathlib import Path
from datetime import datetime, timedelta
from collections import defaultdict

# Fix Windows console encoding
if sys.platform == 'win32':
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')


class CEOBriefing:
    """Generate CEO Briefing reports"""
    
    def __init__(self, vault_path: str):
        self.vault_path = Path(vault_path).expanduser().resolve()
        self.done_dir = self.vault_path / 'Done'
        self.accounting_dir = self.vault_path / 'Accounting'
        self.briefings_dir = self.vault_path / 'Briefings'
        self.logs_dir = self.vault_path / 'Logs'
        self.goals_file = self.vault_path / 'Business_Goals.md'
        self.dashboard_file = self.vault_path / 'Dashboard.md'
        
        self.briefings_dir.mkdir(parents=True, exist_ok=True)
    
    def generate_weekly(self, weeks_ago: int = 0) -> str:
        """Generate weekly briefing"""
        end_date = datetime.now() - timedelta(weeks=weeks_ago)
        start_date = end_date - timedelta(days=6)  # Monday to Sunday
        
        return self._generate_briefing(start_date, end_date, "Weekly")
    
    def generate_monthly(self, months_ago: int = 0) -> str:
        """Generate monthly briefing"""
        end_date = datetime.now()
        if months_ago > 0:
            end_date = end_date.replace(month=end_date.month - months_ago)
        
        # First day of month
        start_date = end_date.replace(day=1)
        
        return self._generate_briefing(start_date, end_date, "Monthly")
    
    def _generate_briefing(self, start_date: datetime, end_date: datetime, report_type: str) -> str:
        """Generate briefing for date range"""
        
        # Collect data
        completed_tasks = self._get_completed_tasks(start_date, end_date)
        revenue_data = self._get_revenue_data(start_date, end_date)
        email_stats = self._get_email_stats(start_date, end_date)
        bottlenecks = self._analyze_bottlenecks(completed_tasks)
        suggestions = self._generate_suggestions(revenue_data, completed_tasks)
        
        # Get business goals
        goals = self._load_business_goals()
        
        # Generate report
        report = f'''---
generated: {datetime.now().isoformat()}
period: {start_date.strftime('%Y-%m-%d')} to {end_date.strftime('%Y-%m-%d')}
report_type: {report_type}
---

# {report_type} CEO Briefing

## Executive Summary
{self._generate_executive_summary(revenue_data, completed_tasks, bottlenecks)}

## Revenue
{self._format_revenue_section(revenue_data, goals)}

## Completed Tasks ({len(completed_tasks)} total)
{self._format_tasks_section(completed_tasks)}

## Bottlenecks
{self._format_bottlenecks_section(bottlenecks)}

## Communication Stats
- **Emails Processed:** {email_stats.get('processed', 0)}
- **Emails Sent:** {email_stats.get('sent', 0)}
- **Avg Response Time:** {email_stats.get('avg_response', 'N/A')}

## Proactive Suggestions
{self._format_suggestions_section(suggestions)}

## Upcoming Deadlines
{self._get_upcoming_deadlines(goals)}

---
*Generated by AI Employee Gold Tier - CEO Briefing Generator*
'''
        
        # Save report
        filename = f"{end_date.strftime('%Y-%m-%d')}_Briefing.md"
        filepath = self.briefings_dir / filename
        filepath.write_text(report, encoding='utf-8')
        
        return str(filepath)
    
    def _get_completed_tasks(self, start_date: datetime, end_date: datetime) -> list:
        """Get tasks completed in date range"""
        tasks = []
        
        if not self.done_dir.exists():
            return tasks
        
        for f in self.done_dir.glob('*.md'):
            try:
                content = f.read_text(encoding='utf-8')
                # Look for completion date in content or file modification time
                mtime = datetime.fromtimestamp(f.stat().st_mtime)
                
                if start_date <= mtime <= end_date:
                    tasks.append({
                        'file': f.name,
                        'completed': mtime,
                        'content': content[:500]  # First 500 chars
                    })
            except:
                continue
        
        return tasks
    
    def _get_revenue_data(self, start_date: datetime, end_date: datetime) -> dict:
        """Get revenue data from accounting folder"""
        revenue = {'total': 0, 'invoices': [], 'expenses': []}
        
        if not self.accounting_dir.exists():
            return revenue
        
        # Look for invoice files
        for f in self.accounting_dir.glob('*.md'):
            try:
                content = f.read_text(encoding='utf-8')
                
                # Simple parsing for amount
                if 'amount:' in content.lower() or '$' in content:
                    # Extract dollar amounts
                    import re
                    amounts = re.findall(r'\$[\d,]+(?:\.\d+)?', content)
                    for amt in amounts:
                        value = float(amt.replace('$', '').replace(',', ''))
                        if 'invoice' in content.lower():
                            revenue['total'] += value
                            revenue['invoices'].append({
                                'file': f.name,
                                'amount': value
                            })
            except:
                continue
        
        return revenue
    
    def _get_email_stats(self, start_date: datetime, end_date: datetime) -> dict:
        """Get email statistics from logs"""
        stats = {'processed': 0, 'sent': 0}
        
        # Check email logs
        email_log_dir = self.logs_dir / 'emails'
        if email_log_dir.exists():
            for log_file in email_log_dir.glob('*.log'):
                try:
                    mtime = datetime.fromtimestamp(log_file.stat().st_mtime)
                    if start_date <= mtime <= end_date:
                        with open(log_file, 'r', encoding='utf-8') as f:
                            lines = f.readlines()
                            stats['sent'] += len(lines)
                except:
                    continue
        
        # Count email action files
        for f in self.done_dir.glob('EMAIL_*.md'):
            try:
                mtime = datetime.fromtimestamp(f.stat().st_mtime)
                if start_date <= mtime <= end_date:
                    stats['processed'] += 1
            except:
                continue
        
        return stats
    
    def _analyze_bottlenecks(self, tasks: list) -> list:
        """Analyze tasks for bottlenecks"""
        bottlenecks = []
        
        # Group tasks by type
        task_types = defaultdict(list)
        for task in tasks:
            if 'EMAIL' in task['file']:
                task_types['email'].append(task)
            elif 'FILE' in task['file']:
                task_types['file'].append(task)
            elif 'LINKEDIN' in task['file']:
                task_types['linkedin'].append(task)
        
        # Look for patterns (e.g., tasks taking too long)
        for task_type, type_tasks in task_types.items():
            if len(type_tasks) > 10:  # More than 10 tasks might indicate bottleneck
                bottlenecks.append({
                    'type': task_type,
                    'count': len(type_tasks),
                    'issue': f'High volume of {task_type} tasks'
                })
        
        return bottlenecks
    
    def _generate_suggestions(self, revenue: dict, tasks: list) -> list:
        """Generate proactive suggestions"""
        suggestions = []
        
        # Revenue-based suggestions
        if revenue['total'] < 5000:  # Less than $5k
            suggestions.append({
                'category': 'Revenue',
                'suggestion': 'Consider reaching out to past clients for new projects',
                'priority': 'high'
            })
        
        # Task-based suggestions
        email_tasks = [t for t in tasks if 'EMAIL' in t['file']]
        if len(email_tasks) > 20:
            suggestions.append({
                'category': 'Efficiency',
                'suggestion': 'High email volume - consider email templates for common responses',
                'priority': 'medium'
            })
        
        return suggestions
    
    def _load_business_goals(self) -> dict:
        """Load business goals from file"""
        goals = {'revenue_target': 10000, 'projects': []}
        
        if self.goals_file.exists():
            content = self.goals_file.read_text(encoding='utf-8')
            
            # Parse revenue target
            import re
            matches = re.findall(r'Monthly goal:?\s*\$?([\d,]+)', content, re.IGNORECASE)
            if matches:
                goals['revenue_target'] = float(matches[0].replace(',', ''))
        
        return goals
    
    def _generate_executive_summary(self, revenue: dict, tasks: list, bottlenecks: list) -> str:
        """Generate executive summary text"""
        summary_parts = []
        
        # Revenue status
        if revenue['total'] > 0:
            summary_parts.append(f"Revenue of ${revenue['total']:,.2f} generated.")
        
        # Task completion
        summary_parts.append(f"Completed {len(tasks)} tasks.")
        
        # Bottlenecks
        if bottlenecks:
            summary_parts.append(f"{len(bottlenecks)} bottleneck(s) identified.")
        else:
            summary_parts.append("No major bottlenecks detected.")
        
        return ' '.join(summary_parts)
    
    def _format_revenue_section(self, revenue: dict, goals: dict) -> str:
        """Format revenue section of report"""
        total = revenue['total']
        target = goals.get('revenue_target', 10000)
        percentage = (total / target * 100) if target > 0 else 0
        
        lines = [
            f"- **Total**: ${total:,.2f}",
            f"- **Target**: ${target:,.2f}",
            f"- **Progress**: {percentage:.1f}%",
            f"- **Invoices**: {len(revenue.get('invoices', []))}"
        ]
        
        return '\n'.join(lines)
    
    def _format_tasks_section(self, tasks: list) -> str:
        """Format tasks section"""
        if not tasks:
            return "*No tasks completed in this period*"
        
        lines = []
        for task in tasks[:10]:  # Show first 10
            lines.append(f"- [x] {task['file'][:60]}...")
        
        if len(tasks) > 10:
            lines.append(f"- ... and {len(tasks) - 10} more")
        
        return '\n'.join(lines)
    
    def _format_bottlenecks_section(self, bottlenecks: list) -> str:
        """Format bottlenecks section"""
        if not bottlenecks:
            return "*No bottlenecks identified*"
        
        lines = ["| Issue | Count | Status |"]
        lines.append("|-------|-------|--------|")
        
        for b in bottlenecks:
            lines.append(f"| {b['issue']} | {b['count']} | Review needed |")
        
        return '\n'.join(lines)
    
    def _format_suggestions_section(self, suggestions: list) -> str:
        """Format suggestions section"""
        if not suggestions:
            return "*No suggestions at this time*"
        
        lines = []
        for s in suggestions:
            lines.append(f"### {s['category']}")
            lines.append(f"- {s['suggestion']} (Priority: {s['priority']})")
            lines.append("")
        
        return '\n'.join(lines)
    
    def _get_upcoming_deadlines(self, goals: dict) -> str:
        """Get upcoming deadlines"""
        # This would parse project deadlines from Business_Goals.md
        return "*No upcoming deadlines tracked*"


def main():
    parser = argparse.ArgumentParser(description='CEO Briefing Generator')
    parser.add_argument('--vault', '-v', default='.', help='Path to Obsidian vault')
    parser.add_argument('--period', '-p', default='last_week',
                        choices=['yesterday', 'last_week', 'last_month', 'this_month'],
                        help='Report period')
    
    args = parser.parse_args()
    
    briefing = CEOBriefing(args.vault)
    
    if args.period == 'last_week':
        filepath = briefing.generate_weekly()
    elif args.period == 'last_month':
        filepath = briefing.generate_monthly()
    elif args.period == 'this_month':
        # Generate for current month
        end_date = datetime.now()
        start_date = end_date.replace(day=1)
        filepath = briefing._generate_briefing(start_date, end_date, "Monthly")
    else:
        # Yesterday
        yesterday = datetime.now() - timedelta(days=1)
        filepath = briefing._generate_briefing(yesterday, yesterday, "Daily")
    
    print(f'✅ Briefing generated: {filepath}')
    print()
    print('View with:')
    print(f'  type "{filepath}"')


if __name__ == '__main__':
    main()
